"""
Django settings for kodtjänst project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import rest_framework
# from kodtjanst.parsers import JSONParser

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'c8-vxfv$-i!yruqix%jn1!3b6-2#a_wgc=fsym4s@=)lm$q5q1'



ALLOWED_HOSTS = ['vgrinformatik.se', '127.0.0.1', 'localhost']



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'kodtjanst',
    'crispy_forms',
    'django_extensions',
    'data_wizard',
    'data_wizard.sources',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'settings.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates','templates/admin'],
        'APP_DIRS': False,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'loaders' : [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
        ],
        },
    },
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'

# DATA_WIZARD = {
#     'BACKEND': 'data_wizard.backends.threading',
#     'LOADER': ['data_wizard.loaders.FileLoader','kodtjanst.loaders.CustomJsonUrlLoader'],
#     'IDMAP': 'data_wizard.idmap.never',   # 'data_wizard.idmap.existing' in 2.0
#     'AUTHENTICATION': 'rest_framework.authentication.SessionAuthentication',
#     'PERMISSION': 'rest_framework.permissions.IsAdminUser',
# }

# from kodtjanst.parsers import SnomedJSONParser

# REST_FRAMEWORK = {
#     'DEFAULT_PARSER_CLASSES': [
#         'rest_framework.parsers.JSONParser',
#         # 'parsers.SnomedJSONParser',
#         # 'rest_framework.parsers.FileUploadParser',
#         #'rest_framework.parsers.DjangoMultiPartParser',
#         'rest_framework.parsers.FormParser'

#     ]
# }

WSGI_APPLICATION = 'settings.wsgi.application'

DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Stockholm'

USE_I18N = True

USE_L10N = True

USE_TZ = True