# Generated by Django 3.0.3 on 2020-04-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodtjänst', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codetext',
            name='code_andra_definition',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
