# Generated by Django 3.0.3 on 2020-04-08 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternaKodverk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namn', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('kodterm_url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kodtext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodtext', models.CharField(max_length=255)),
                ('kod', models.CharField(max_length=255)),
                ('definition', models.TextField(max_length=500, null=True)),
                ('andra_definition', models.TextField(max_length=500, null=True)),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MappadTillKodtext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mappad_id', models.CharField(max_length=255)),
                ('mappad_kodverk', models.URLField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kodtjanst.Kodtext')),
            ],
        ),
        migrations.CreateModel(
            name='Kodverk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('är_ett_urval', models.BooleanField(null=True)),
                ('syfte', models.TextField(max_length=1000, null=True)),
                ('rubrik_på_kodverk', models.CharField(max_length=255, null=True)),
                ('kort_beskrivning', models.TextField(max_length=1000, null=True)),
                ('giltig_från', models.DateField(null=True)),
                ('giltig_tom', models.DateField(null=True)),
                ('kodschema', models.CharField(max_length=255, null=True)),
                ('identifier', models.CharField(max_length=255, null=True)),
                ('version', models.FloatField(null=True)),
                ('källa', models.CharField(max_length=255, null=True)),
                ('typ_av_kodverk', models.CharField(max_length=255, null=True)),
                ('ämnesområde', models.CharField(max_length=255, null=True)),
                ('instruktion_för_kodverket', models.CharField(max_length=255, null=True)),
                ('ägare', models.CharField(max_length=255, null=True)),
                ('ansvarig', models.CharField(max_length=255, null=True)),
                ('mappning_för_rapportering', models.BooleanField(null=True)),
                ('språk', models.CharField(choices=[('svenska', 'svenska'), ('engelska', 'engelska')], default='svenska', max_length=25, null=True)),
                ('uppdateringsintervall', models.DurationField(null=True)),
                ('version_av_källa', models.CharField(max_length=50, null=True)),
                ('system_som_använderkodverket', models.CharField(max_length=255, null=True)),
                ('kategori', models.CharField(max_length=255, null=True)),
                ('beskrivning_av_informationsbehov', models.TextField(null=True)),
                ('urval_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kodtjanst.Kodverk')),
                ('ändrad_av', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='kodtext',
            name='kodverk',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.PROTECT, to='kodtjanst.Kodverk'),
        ),
    ]
