# Generated by Django 3.0.6 on 2020-06-17 11:33

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('kodtjanst', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kodtext',
            name='extra_data',
            field=django_mysql.models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='kodverk',
            name='extra_data',
            field=django_mysql.models.JSONField(default=dict, null=True),
        ),
    ]
