# Generated by Django 3.0.3 on 2020-04-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodtjanst', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externakodverk',
            options={'verbose_name_plural': 'Externa Kodverk'},
        ),
        migrations.AlterModelOptions(
            name='kodtext',
            options={'verbose_name_plural': 'Kodtexter'},
        ),
        migrations.AlterModelOptions(
            name='kodverk',
            options={'verbose_name_plural': 'Kodverk'},
        ),
        migrations.AlterModelOptions(
            name='mappadtillkodtext',
            options={'verbose_name_plural': 'Mappad Kodtexter'},
        ),
        migrations.AlterField(
            model_name='kodverk',
            name='typ_av_kodverk',
            field=models.CharField(choices=[('Inget', 'Inget'), ('Administrativ', 'Administrativ'), ('Klinisk', 'Klinisk')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kodverk',
            name='uppdateringsintervall',
            field=models.DurationField(choices=[('Årligen', 'Årligen'), ('Månadsvis', 'Månadsvis'), ('Veckovis', 'Veckovis'), ('Dagligen', 'Dagligen'), ('Vid behov', 'Vid behov'), ('Ej aktuellt', 'Ej aktuellt')], null=True),
        ),
        migrations.AlterField(
            model_name='kodverk',
            name='ägare',
            field=models.CharField(choices=[('Inera', 'Inera'), ('Socialstyrelsen', 'Socialstyrelsen'), ('Västra Götalandsregionen', 'Västra Götalandsregionen')], max_length=255, null=True),
        ),
    ]
