# Generated by Django 3.0.3 on 2020-04-08 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kodtjänst', '0002_codetext_code_andra_definition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kodtext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodtext', models.CharField(max_length=255)),
                ('kod', models.CharField(max_length=255)),
                ('definition', models.TextField(max_length=500, null=True)),
                ('andra_definition', models.TextField(max_length=500, null=True)),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='CodeSet',
            new_name='Kodverk',
        ),
        migrations.RenameModel(
            old_name='MappedToCodeTerm',
            new_name='MappadTillKodtext',
        ),
        migrations.DeleteModel(
            name='CodeText',
        ),
        migrations.AddField(
            model_name='kodtext',
            name='kodverk',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.PROTECT, to='kodtjänst.Kodverk'),
        ),
        migrations.AlterField(
            model_name='mappadtillkodtext',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kodtjänst.Kodtext'),
        ),
    ]
