# Generated by Django 3.0.3 on 2020-05-18 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kodtjanst', '0002_auto_20200414_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kodverk',
            name='är_ett_urval',
        ),
    ]
