# Generated by Django 3.0.6 on 2020-06-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodtjanst', '0002_auto_20200619_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kodverk',
            name='kodverk_variant',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='kodverk',
            name='ägare_av_kodverk',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
