# Generated by Django 3.0.6 on 2020-06-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodtjanst', '0003_auto_20200622_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kodtext',
            name='annan_kodtext',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kodtext',
            name='status',
            field=models.CharField(blank=True, choices=[('Design', 'Design'), ('Bygg', 'Bygg'), ('Beslutad', 'Beslutad'), ('Utjast', 'Utkast'), ('Okänt', 'Okänt')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kodverk',
            name='status',
            field=models.CharField(blank=True, choices=[('Design', 'Design'), ('Bygg', 'Bygg'), ('Beslutad', 'Beslutad'), ('Utjast', 'Utkast'), ('Okänt', 'Okänt')], max_length=25, null=True),
        ),
    ]
