# Generated by Django 3.0.3 on 2020-05-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodtjanst', '0003_remove_kodverk_är_ett_urval'),
    ]

    operations = [
        migrations.AddField(
            model_name='kodverk',
            name='kodverk_variant',
            field=models.CharField(choices=[('Kodverk', 'Kodverk'), ('Kodset', 'Kodset'), ('Alfa respons', 'Alfa respons'), ('Urval', 'Urval')], default=1, max_length=12),
            preserve_default=False,
        ),
    ]
