# Generated by Django 3.0.3 on 2020-04-08 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kodtjänst', '0003_auto_20200408_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='kodverk',
            name='urval_refernce',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kodtjänst.Kodverk'),
        ),
    ]
