# Generated by Django 3.0.6 on 2020-06-24 09:03

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('kodtjanst', '0004_auto_20200622_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kodverk',
            name='extra_data',
            field=django_mysql.models.JSONField(default=dict, help_text='Data behöver vara i JSON format dvs {"nyckel" : "värde"} <br> t.ex {"millenium_code_value": 22897599} och kan kan hierarkiska nivåer', null=True),
        ),
        migrations.AlterField(
            model_name='kodverk',
            name='kodverk_variant',
            field=models.CharField(blank=True, choices=[('kodverk', 'kodverk'), ('code set', 'code set'), ('alpha response', 'alpha response'), ('urval', 'urval')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='kodverk',
            name='urval_referens',
            field=models.ForeignKey(blank=True, help_text='Välja kodverket som är huvud kodverket', null=True, on_delete=django.db.models.deletion.CASCADE, to='kodtjanst.Kodverk'),
        ),
    ]
