# Generated by Django 3.0.3 on 2020-05-26 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kodtjanst', '0004_kodverk_kodverk_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='kodtext',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kodtext',
            name='ändrat_av',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kodverk',
            name='urval_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kodtjanst.Kodverk'),
        ),
    ]
