# Generated by Django 3.0.3 on 2020-05-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodtjanst', '0006_auto_20200526_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kodverk',
            name='uppdateringsintervall',
            field=models.CharField(choices=[('Årligen', 'Årligen'), ('Månadsvis', 'Månadsvis'), ('Veckovis', 'Veckovis'), ('Dagligen', 'Dagligen'), ('Vid behov', 'Vid behov'), ('Ej aktuellt', 'Ej aktuellt')], max_length=20, null=True),
        ),
    ]
