# Generated by Django 3.0.6 on 2020-07-13 11:14

import django.core.validators
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('kodtjanst', '0006_auto_20200624_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kodtext',
            name='kod',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kodverk',
            name='beskrivning_av_informationsbehov',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kodverk',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='Data behöver vara i JSON format dvs {"nyckel" : "värde"} <br> t.ex {"millenium_code_value": 22897599} och kan kan hierarkiska nivåer', null=True),
        ),
        migrations.AlterField(
            model_name='kodverk',
            name='giltig_från',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kodverk',
            name='giltig_tom',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kodverk',
            name='identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kodverk',
            name='instruktion_för_kodverket',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kodverk',
            name='kodschema',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kodverk',
            name='kommentar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kodverk',
            name='kort_beskrivning',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='kodverk',
            name='källa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kodverk',
            name='syfte',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='kodverk',
            name='system_som_använderkodverket',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kodverk',
            name='uppdateringsintervall',
            field=models.CharField(blank=True, choices=[('Årligen', 'Årligen'), ('Månadsvis', 'Månadsvis'), ('Veckovis', 'Veckovis'), ('Dagligen', 'Dagligen'), ('Vid behov', 'Vid behov'), ('Ej aktuellt', 'Ej aktuellt')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kodverk',
            name='version',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='kodverk',
            name='version_av_källa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mappadtillkodtext',
            name='kommentar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
