# Generated by Django 3.0.3 on 2020-05-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodtjanst', '0007_auto_20200526_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kodtext',
            name='andra_definition',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='kodtext',
            name='definition',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='kodtext',
            name='position',
            field=models.PositiveIntegerField(),
        ),
    ]
