# Generated by Django 3.0.6 on 2020-07-14 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodtjanst', '0007_auto_20200713_1314'),
    ]

    operations = [migrations.AlterField(
            model_name='kodverk',
            name='version',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
