# Generated by Django 3.0.6 on 2020-10-20 09:55

from django.db import migrations
import kodtjanst.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kodtjanst', '0008_auto_20200714_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kodtext',
            name='extra_data',
            field=kodtjanst.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='kodverk',
            name='extra_data',
            field=kodtjanst.fields.JSONField(blank=True, help_text='Data behöver vara i JSON format dvs {"nyckel" : "värde"} <br> t.ex {"millenium_code_value": 22897599} och kan kan hierarkiska nivåer', null=True),
        ),
    ]
