# Generated by Django 3.1.2 on 2020-10-30 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kodtjanst', '0009_auto_20201028_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kodtext',
            name='kodverk',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='kodtjanst.kodverk'),
        ),
        migrations.AlterField(
            model_name='mappadtillkodtext',
            name='kodtext',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kodtjanst.kodtext'),
        ),
        migrations.AlterField(
            model_name='nyckelord',
            name='kodverk_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kodtjanst.kodtext'),
        ),
        migrations.AlterField(
            model_name='ämne',
            name='kodverk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kodtjanst.kodverk'),
        ),
    ]
