# Generated by Django 3.1.2 on 2020-10-30 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kodtjanst', '0010_auto_20201030_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kodtext',
            name='kodverk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kodtjanst.kodverk'),
        ),
    ]
