# Generated by Django 3.1.2 on 2020-11-05 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kodtjanst', '0012_auto_20201104_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ämne',
            old_name='domän_id',
            new_name='id',
        ),
    ]
