# Generated by Django 3.1.2 on 2020-11-16 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodtjanst', '0013_auto_20201105_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kodverk',
            old_name='källa',
            new_name='hämtnings_källa',
        ),
        migrations.RemoveField(
            model_name='kodverk',
            name='kodschema',
        ),
        migrations.RemoveField(
            model_name='kodverk',
            name='kommentar',
        ),
        migrations.RemoveField(
            model_name='kodverk',
            name='kort_beskrivning',
        ),
        migrations.RemoveField(
            model_name='kodverk',
            name='språk',
        ),
        migrations.RemoveField(
            model_name='kodverk',
            name='system_som_använderkodverket',
        ),
        migrations.AddField(
            model_name='kodverk',
            name='ansvarig_förvaltare',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kodverk',
            name='giltig_från',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='kodverk',
            name='giltig_tom',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='kodverk',
            name='syfte',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='kodverk',
            name='version',
            field=models.FloatField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='kodverk',
            name='version_av_källa',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kodverk',
            name='ägare_av_kodverk',
            field=models.CharField(choices=[('Inera', 'Inera'), ('Socialstyrelsen', 'Socialstyrelsen'), ('Västra Götalandsregionen', 'Västra Götalandsregionen'), ('Skatteverket', 'Skatteverket')], max_length=255, null=True),
        ),
    ]
