# Generated by Django 3.1.2 on 2020-11-17 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kodtjanst', '0014_auto_20201116_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kodverk',
            old_name='rubrik_på_kodverk',
            new_name='titel_på_kodverk',
        ),
    ]
