# Generated by Django 3.1.2 on 2020-11-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodtjanst', '0015_auto_20201117_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kodverk',
            name='status',
            field=models.CharField(blank=True, choices=[('Publicera ej', 'Publicera ej'), ('Beslutad', 'Beslutad')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='kodverk',
            name='version_av_källa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
