# Generated by Django 3.1.2 on 2020-11-25 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kodtjanst', '0017_auto_20201124_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kodtext',
            name='status',
            field=models.CharField(blank=True, choices=[('Publicera ej', 'Publicera ej'), ('Beslutad', 'Beslutad'), ('Utkast', 'Utkast'), ('Okänt', 'Okänt')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mappadtillkodtext',
            name='kodtext',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kodtjanst.kodverk'),
        ),
    ]
