# Generated by Django 3.1.2 on 2020-11-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodtjanst', '0018_auto_20201125_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='kodverk',
            name='användning_av_kodverk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
