# Generated by Django 3.1.2 on 2020-11-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodtjanst', '0020_auto_20201126_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kodtext',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kodtext',
            name='kommentar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kodtext',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
