# Generated by Django 3.1.2 on 2020-11-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodtjanst', '0021_auto_20201126_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kodverk',
            name='ägare_till_kodverk',
            field=models.CharField(choices=[('Informatik', 'Informatik'), ('Inera', 'Inera'), ('Socialstyrelsen', 'Socialstyrelsen'), ('Västra Götalandsregionen', 'Västra Götalandsregionen'), ('Skatteverket', 'Skatteverket'), ('Snomed International', 'Snomed International')], max_length=255, null=True),
        ),
    ]
