# Generated by Django 3.1.2 on 2020-11-27 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodtjanst', '0022_auto_20201127_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kodverk',
            name='giltig_tom',
            field=models.DateField(default=datetime.date(2099, 12, 31), null=True),
        ),
        migrations.AlterField(
            model_name='ämne',
            name='domän_kontext',
            field=models.TextField(blank=True, null=True),
        ),
    ]
