# Generated by Django 3.1.2 on 2020-11-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodtjanst', '0023_auto_20201127_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kodtext',
            name='extra_data',
            field=models.JSONField(blank=True, help_text='Data behöver vara i JSON format dvs {"nyckel" : "värde"} <br> t.ex {"millenium_code_value": 22897599} och kan ha hierarkiska nivåer', null=True),
        ),
        migrations.AlterField(
            model_name='kodverk',
            name='extra_data',
            field=models.JSONField(blank=True, help_text='Data behöver vara i JSON format dvs {"nyckel" : "värde"} <br> t.ex {"millenium_code_value": 22897599} och kan ha hierarkiska nivåer', null=True),
        ),
    ]
