# Generated by Django 3.1.2 on 2020-12-08 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kodtjanst', '0024_auto_20201127_1307'),
    ]

    operations = [

        migrations.RenameModel(
            old_name='MappadTillKodtext',
            new_name='ExternaKodtext',
        ),
        migrations.AlterModelOptions(
            name='externakodtext',
            options={'verbose_name_plural': 'Externa Kodtext'},
        ),
        migrations.AlterField(
            model_name='externakodtext',
            name='kodtext',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kodtjanst.kodtext'),
        ),
        migrations.DeleteModel(
            name='Ämne',
        ),
    ]
