# Generated by Django 3.1.2 on 2020-12-09 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kodtjanst', '0025_auto_20201208_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidatedBy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('domän_kontext', models.TextField(blank=True, null=True)),
                ('domän_stream', models.CharField(max_length=255, null=True)),
                ('domän_epost', models.EmailField(max_length=254, null=True)),
                ('domän_telefon', models.CharField(max_length=255, null=True)),
                ('kodverk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kodtjanst.kodverk')),
            ],
            options={
                'verbose_name_plural': 'Verifierad av',
            },
        ),
    ]
