# Generated by Django 3.1.2 on 2020-12-10 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kodtjanst', '0026_validatedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validatedby',
            name='domän_kontext',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.CreateModel(
            name='CommentedKodverk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_name', models.CharField(max_length=255, null=True)),
                ('comment_epost', models.EmailField(max_length=254, null=True)),
                ('comment_telefon', models.CharField(max_length=255, null=True)),
                ('comment_kontext', models.TextField(max_length=2000, null=True)),
                ('kodverk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kodtjanst.kodverk')),
            ],
            options={
                'verbose_name_plural': 'Kommenterade kodverk',
            },
        ),
    ]
