# Generated by Django 3.1.2 on 2020-12-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodtjanst', '0027_auto_20201210_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiKodtextMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_description', models.CharField(blank=True, max_length=255, null=True)),
                ('order_dictionary', models.JSONField(blank=True, help_text='Ordning av attributer som mappas', null=True)),
                ('kodtext_from', models.ManyToManyField(related_name='field_from', to='kodtjanst.Kodtext')),
                ('kodtext_to', models.ManyToManyField(related_name='field_to', to='kodtjanst.Kodtext')),
            ],
        ),
    ]
