# Generated by Django 3.1.2 on 2021-02-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodtjanst', '0028_multikodtextmapping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nyckelord',
            options={'verbose_name_plural': 'Sökord'},
        ),
        migrations.RenameField(
            model_name='nyckelord',
            old_name='kodverk_id',
            new_name='kodverk_from',
        ),
        migrations.AlterField(
            model_name='validatedby',
            name='domän_telefon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
