# Generated by Django 3.1.2 on 2021-03-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodtjanst', '0031_auto_20210315_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kodverk',
            name='ägare_till_kodverk',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
