# Generated by Django 3.1.2 on 2021-04-09 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kodtjanst', '0032_auto_20210324_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeableConceptAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('källa', models.CharField(blank=True, max_length=255, null=True)),
                ('version_av_källa', models.CharField(blank=True, max_length=50, null=True)),
                ('ansvarig_förvaltare', models.CharField(max_length=255, null=True)),
                ('ägare_till_kodverk', models.CharField(max_length=255, null=True)),
                ('kodverk_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kodtjanst.kodverk')),
            ],
            options={
                'verbose_name_plural': 'Attributer som kan ha flera värde',
            },
        ),
    ]
