# Generated by Django 3.1.2 on 2021-04-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodtjanst', '0033_codeableconceptattributes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codeableconceptattributes',
            options={'verbose_name_plural': 'Attribut som kan ha flera värde'},
        ),
        migrations.AlterField(
            model_name='kodverk',
            name='kodverk_variant',
            field=models.CharField(blank=True, choices=[('kodverk', 'kodverk'), ('codeable concept', 'codeable concept'), ('code set', 'code set'), ('alpha response', 'alpha response'), ('urval', 'urval')], max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='kodverk',
            name='status',
            field=models.CharField(blank=True, choices=[('Publicera ej', 'Publicera ej'), ('Beslutad', 'Beslutad'), ('Inaktiv', 'Inaktiv')], max_length=25, null=True),
        ),
    ]
