# Generated by Django 3.1.2 on 2021-04-12 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kodtjanst', '0034_auto_20210412_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kodverk',
            name='ansvarig_förvaltare',
        ),
        migrations.RemoveField(
            model_name='kodverk',
            name='källa',
        ),
        migrations.RemoveField(
            model_name='kodverk',
            name='version_av_källa',
        ),
        migrations.RemoveField(
            model_name='kodverk',
            name='ägare_till_kodverk',
        ),
    ]
