# Generated by Django 3.1.2 on 2021-04-28 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kodtjanst', '0035_auto_20210412_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kodverk',
            name='ansvarig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ansvarig_person', to=settings.AUTH_USER_MODEL, verbose_name='Ansvarig person'),
        ),
        migrations.AlterField(
            model_name='kodverk',
            name='beskrivning_av_informationsbehov',
            field=models.TextField(blank=True, null=True, verbose_name='Beskrivning av innehållet'),
        ),
        migrations.AlterField(
            model_name='kodverk',
            name='status',
            field=models.CharField(blank=True, choices=[('Publicera ej', 'Publicera ej'), ('Aktiv', 'Aktiv'), ('Inaktiv', 'Inaktiv')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='kodverk',
            name='uppdateringsintervall',
            field=models.CharField(blank=True, choices=[('Årligen', 'Årligen'), ('Halvårsvis', 'Halvårsvis'), ('Vid behov', 'Vid behov')], max_length=20, null=True),
        ),
    ]
