# Generated by Django 3.1.2 on 2021-05-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodtjanst', '0037_auto_20210504_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentedkodverk',
            name='comment_status',
            field=models.CharField(choices=[('Pågår', 'Pågår'), ('Klart', 'Klart'), ('Nytt', 'Nytt')], max_length=5, null=True),
        ),
    ]
