# Generated by Django 3.1.2 on 2021-05-11 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kodtjanst', '0038_commentedkodverk_comment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentedkodverk',
            name='comment_datum',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
