# Generated by Django 3.1.2 on 2021-05-19 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kodtjanst', '0039_commentedkodverk_comment_datum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentedkodverk',
            old_name='comment_datum',
            new_name='datum_skapat',
        ),
        migrations.RenameField(
            model_name='commentedkodverk',
            old_name='comment_epost',
            new_name='epost',
        ),
        migrations.RenameField(
            model_name='commentedkodverk',
            old_name='comment_kontext',
            new_name='kommentar',
        ),
        migrations.RenameField(
            model_name='commentedkodverk',
            old_name='comment_telefon',
            new_name='kontakt',
        ),
        migrations.RenameField(
            model_name='commentedkodverk',
            old_name='comment_name',
            new_name='namn',
        ),
        migrations.RenameField(
            model_name='commentedkodverk',
            old_name='comment_status',
            new_name='status',
        ),
        migrations.AddField(
            model_name='commentedkodverk',
            name='handläggare',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kommentar_handläggare', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentedkodverk',
            name='handläggnings_kommentar',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
