# Generated by Django 3.1.2 on 2021-06-22 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kodtjanst', '0042_auto_20210618_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArbetsKommentar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kommentar', models.TextField(blank=True, max_length=5000, null=True)),
                ('angivet_av', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='angivet_av', to=settings.AUTH_USER_MODEL, verbose_name='Angivet av person')),
                ('kodverk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kodtjanst.kodverk')),
            ],
            options={
                'verbose_name_plural': 'Arbets Kommentar',
            },
        ),
        migrations.DeleteModel(
            name='ValidatedBy',
        ),
    ]
