# Generated by Django 3.1.2 on 2021-09-20 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kodtjanst', '0045_historicalarbetskommentar_historicalcodeableconceptattributes_historicalkodtext_historicalkodverk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalkodverk',
            name='datum_skapat',
        ),
    ]
