# Generated by Django 3.1.2 on 2022-01-24 10:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kodtjanst', '0047_auto_20220117_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='externakodtext',
            name='kodverk',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='kodtjanst.kodverk'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalkodverk',
            name='giltig_från',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalkodverk',
            name='giltig_tom',
            field=models.DateField(blank=True, default=datetime.date(2099, 12, 31), null=True),
        ),
        migrations.AlterField(
            model_name='kodverk',
            name='giltig_från',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kodverk',
            name='giltig_tom',
            field=models.DateField(blank=True, default=datetime.date(2099, 12, 31), null=True),
        ),
    ]
