# Generated by Django 3.1.2 on 2022-01-24 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kodtjanst', '0048_auto_20220124_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externakodtext',
            name='kodtext',
        ),
    ]
