# Generated by Django 3.2.13 on 2022-08-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodtjanst', '0049_remove_externakodtext_kodtext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externakodtext',
            options={'verbose_name': 'Extern Kodtext', 'verbose_name_plural': 'Externa Kodtexter'},
        ),
        migrations.AlterField(
            model_name='historicalkodverk',
            name='kodverk_variant',
            field=models.CharField(blank=True, choices=[('VGR kodverk', 'VGR kodverk'), ('Externt kodverk hänvisning', 'Externt kodverk hänvisning'), ('VGR codeable concept', 'VGR codeable concept')], help_text='Kodtext fält kommer ändras efter sparande, beroende på valet.', max_length=26, null=True),
        ),
        migrations.AlterField(
            model_name='historicalkodverk',
            name='titel_på_kodverk',
            field=models.CharField(max_length=255, null=True, verbose_name='Namn'),
        ),
        migrations.AlterField(
            model_name='kodverk',
            name='kodverk_variant',
            field=models.CharField(blank=True, choices=[('VGR kodverk', 'VGR kodverk'), ('Externt kodverk hänvisning', 'Externt kodverk hänvisning'), ('VGR codeable concept', 'VGR codeable concept')], help_text='Kodtext fält kommer ändras efter sparande, beroende på valet.', max_length=26, null=True),
        ),
        migrations.AlterField(
            model_name='kodverk',
            name='titel_på_kodverk',
            field=models.CharField(max_length=255, null=True, verbose_name='Namn'),
        ),
    ]
