# Generated by Django 3.2.13 on 2022-08-23 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kodtjanst', '0050_auto_20220823_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalkodverk',
            name='underlag',
        ),
        migrations.RemoveField(
            model_name='kodverk',
            name='underlag',
        ),
    ]
